
= Communication
The goal of a communication system is to transfer information across space and time. To achieve this, a signal needs to be generated by a transmitter in accordance to the information that is intended to be transferred to a receiver. This signal then propagates to a receiver, where the intended information is decoded from the received signal. Therefore, any communication system can be broken down into three major components. The Transmitter, the receiver, and the channel.
On December 29, 1959, Richard Feynman gave a lecture at American Physical Society meeting in Caltech titled, “There’s Plenty of Room at the Bottom” @feynman1959plenty ; In which he asked, How Much can we shrink a communication system? While we haven't found the lower limit for it yet, we do have technologies which can work at the nano scale. The reason why we even need new methods for communication is that the conventional methods, i.e. Electromagnetic(EM) Communication cannot be used due to a large amount of noise being generated at the scale, a large energy requirement not suitable for the nano devices, and the miniaturized antennas being highly inefficient and hard to design. @akyildiz2008nanonetworks @nano_blog_em The Three methods discussed in this papers are used in contemporary nanotech.

1. *Molecular Communication*:
#include "MolecularCommunication.typ"


2. *Electromagnetic Communication*:
#include "ElectroMagneticCommunication.typ"
