
= Communication
The goal of a communication system is to transfer information across space and time. To achieve this, a signal needs to be generated by a transmitter in accordance to the information that is intended to be transferred to a receiver. This signal then propagates to a receiver, where the intended information is decoded from the received signal. Therefore, any communication system can be broken down into three major components. The Transmitter, the receiver, and the channel.

1. *Molecular Communication*:
Molecular Communication is a Biomimetic technology, inspired from Communication in bacteria using chemical signals at Nano and Micro-scale and in the social-insect populations at Macro-Scales using Pheromones; This makes it very bio-compaitable for our applications. 

